/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pixelrake;

import tools.*;

/**
 *
 * @author user
 */
public class ToolPanel extends javax.swing.JPanel {

    
    PaintTool lineTool = new LineTool();
    PaintTool eraserTool = new EraserTool();
    PaintTool pointerTool = new PointerTool();
    PaintTool penTool = new PenTool();
    PaintTool bucketTool = new BucketTool();
    
    PaintTool currentTool = pointerTool;
    
    public ToolPanel() {
        initComponents();
    }

    public PaintTool getCurrentPaintTool(){
        return currentTool;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        select = new javax.swing.JButton();
        eraser = new javax.swing.JButton();
        pen = new javax.swing.JButton();
        line = new javax.swing.JButton();
        pointer = new javax.swing.JButton();
        bucket = new javax.swing.JButton();
        shapes = new javax.swing.JButton();
        shade = new javax.swing.JButton();

        select.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/select.png"))); // NOI18N
        select.setToolTipText("Select");

        eraser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/erase.png"))); // NOI18N
        eraser.setToolTipText("Eraser");
        eraser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eraserActionPerformed(evt);
            }
        });

        pen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pen.png"))); // NOI18N
        pen.setToolTipText("Pen");
        pen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penActionPerformed(evt);
            }
        });

        line.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/line.png"))); // NOI18N
        line.setToolTipText("Line");
        line.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineActionPerformed(evt);
            }
        });

        pointer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pointer.png"))); // NOI18N
        pointer.setToolTipText("Pointer");
        pointer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointerActionPerformed(evt);
            }
        });

        bucket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/buket.png"))); // NOI18N
        bucket.setToolTipText("Bucket");
        bucket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bucketActionPerformed(evt);
            }
        });

        shapes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shapes.png"))); // NOI18N
        shapes.setToolTipText("Shapes");
        shapes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shapesActionPerformed(evt);
            }
        });

        shade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shade.png"))); // NOI18N
        shade.setToolTipText("Shade");
        shade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shadeActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pointer)
                    .add(bucket))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(select)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(pen)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(line)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(eraser)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(shapes)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(shade)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(pointer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(bucket, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(line, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(pen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(select, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(eraser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(shapes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(shade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(294, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineActionPerformed
        currentTool.reset();
        currentTool = lineTool;
    }//GEN-LAST:event_lineActionPerformed

    private void eraserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eraserActionPerformed
        currentTool.reset();
        currentTool = eraserTool;
    }//GEN-LAST:event_eraserActionPerformed

    private void pointerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointerActionPerformed
        currentTool.reset();
        currentTool = pointerTool;
    }//GEN-LAST:event_pointerActionPerformed

    private void penActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penActionPerformed
        currentTool.reset();
        currentTool = penTool;
    }//GEN-LAST:event_penActionPerformed

    private void bucketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bucketActionPerformed
        currentTool.reset();
        currentTool = bucketTool;
    }//GEN-LAST:event_bucketActionPerformed

    private void shapesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shapesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shapesActionPerformed

    private void shadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shadeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bucket;
    private javax.swing.JButton eraser;
    private javax.swing.JButton line;
    private javax.swing.JButton pen;
    private javax.swing.JButton pointer;
    private javax.swing.JButton select;
    private javax.swing.JButton shade;
    private javax.swing.JButton shapes;
    // End of variables declaration//GEN-END:variables
}
